services:
  - type: web
    name: learning-logs
    env: docker
    plan: free
    repo: https://github.com/wengcychan/learning_logs.git
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RENDER_EXTERNAL_HOSTNAME
        value: 0.0.0.0
      - key: PORT
        value: 8000