services:
  - type: web
    name: learning-logs
    env: docker
    plan: free
    repo: https://github.com/wengcychan/learning_logs.git
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RENDER_EXTERNAL_HOSTNAME
        value: 0.0.0.0
    ports:
      - port: 8000
    buildCommand: docker-compose build
    startCommand: docker-compose up learning_logs
    mounts:
      - type: volume
        name: learning_logs
        path: /learning_logs/app